version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mese_database
    restart: always
    environment:
      POSTGRES_DB: mese
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_mese
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres

  app:
    build: .
    container_name: laravel_mese
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
