version: '3.8'

networks:
  mese_network:

services:
  postgres:
    image: postgres:15
    container_name: mese_database
    restart: always
    environment:
      POSTGRES_DB: mese
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: senha
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    networks:
      - mese_network
